// lib/packagesData.js

export const PACKAGE_CATEGORIES = [
  {
    id: "all",
    label: "All Collections",
    shortTitle: "All Packages",
    badge: "15 Curated Options",
    description: "Explore all fine-art studio photography collections for your baby, maternity, or newborn milestone in Lucknow.",
  },
  {
    id: "baby",
    label: "Baby Photography",
    sublabel: "6 Months & Above",
    serviceName: "Baby Photography",
    fallbackServiceId: 11,
    badge: "Milestones 6M+",
    recommendedStage: "Best at 6–12 months (sitting up, crawling & 1st birthday)",
    description:
      "Cherish the playful giggles, first teeth, and milestone smiles with customized setups and handcrafted props in our temperature-controlled studio.",
  },
  {
    id: "maternity",
    label: "Maternity Photoshoot",
    sublabel: "Expecting Mothers",
    serviceName: "Maternity Photoshoot",
    fallbackServiceId: 1,
    badge: "Glowing Bump",
    recommendedStage: "Best at 28–34 weeks when pregnancy glow is at its peak",
    description:
      "Celebrate the sacred beauty of motherhood with fine-art dramatic lighting, complimentary designer gowns, and timeless partner portraits.",
  },
  {
    id: "newborn",
    label: "Newborn Photography",
    sublabel: "5 to 25 Days",
    serviceName: "Newborn Photography",
    fallbackServiceId: 2,
    badge: "Pure Innocence",
    recommendedStage: "Best scheduled between day 5 and day 25 after birth",
    description:
      "Safety-certified gentle newborn posing with sanitized organic wraps, macro detail shots of tiny toes, and soothing temperature-regulated comfort.",
  },
];

export const PACKAGES_DATA = [
  // ==========================================
  // Baby Photography (6 Months & Above)
  // ==========================================
  {
    id: "baby-classic",
    category: "baby",
    title: "Baby Photography - Classic",
    tier: "Classic",
    price: "₹15,000",
    numericPrice: 15000,
    badge: "Essential Milestone",
    isPopular: false,
    duration: "2 Hours",
    editedCount: 10,
    setupsCount: "1 Theme",
    rawIncluded: true,
    description: "Cherish the very first moments of your little one with our package, designed to preserve memories forever.",
    inclusions: [
      "One designed theme.",
      "10 Edited Pictures.",
      "All RAW pictures.",
      "Location: Studio | Duration: 2 Hours",
      "Option to include parents (both mother and father) portraits - Additional: ₹4,500/-",
    ],
    serviceName: "Baby Photography",
    fallbackServiceId: 11,
    whatsappMessage: "Hello Jaya Photography! I'm interested in booking the Baby Photography - Classic package (₹15,000). Please share available dates.",
  },
  {
    id: "baby-premium",
    category: "baby",
    title: "Baby Photography - Premium",
    tier: "Premium",
    price: "₹25,000",
    numericPrice: 25000,
    badge: "Great Value",
    isPopular: false,
    duration: "2 Hours",
    editedCount: 20,
    setupsCount: "2 Setups",
    rawIncluded: true,
    description: "Cherish the very first moments of your little one with our package, designed to preserve memories forever.",
    inclusions: [
      "Two Setups (One Themed + One Plain)",
      "Includes One complimentary dress.",
      "20 Edited Pictures.",
      "All RAW pictures",
      "Location: Studio | Duration: 2 Hours",
      "Option to include parents (both mother and father) portraits - Additional: ₹4,500/-",
    ],
    serviceName: "Baby Photography",
    fallbackServiceId: 11,
    whatsappMessage: "Hello Jaya Photography! I'm interested in booking the Baby Photography - Premium package (₹25,000). Please share available dates.",
  },
  {
    id: "baby-blossom",
    category: "baby",
    title: "Baby Photography - Blossom",
    tier: "Blossom",
    price: "₹35,000",
    numericPrice: 35000,
    badge: "Most Loved",
    isPopular: true,
    duration: "3+ Hours",
    editedCount: 20,
    setupsCount: "2 Setups (Plain + Themed)",
    rawIncluded: true,
    description: "A perfect choice for capturing your little one's special half-year and above milestones with simplicity and elegance.",
    inclusions: [
      "1 setup with plain or minimal décor.",
      "1 customized themed décor setup, designed as per your preference.",
      "20 professionally edited images.",
      "All raw images provided.",
      "Location: Studio | Duration: 3 + Hours",
    ],
    serviceName: "Baby Photography",
    fallbackServiceId: 11,
    whatsappMessage: "Hello Jaya Photography! I would love to book the Baby Photography - Blossom package (₹35,000). Please let me know availability.",
  },
  {
    id: "baby-radiance",
    category: "baby",
    title: "Baby Photography - Radiance",
    tier: "Radiance",
    price: "₹40,000",
    numericPrice: 40000,
    badge: "Family Favorite",
    isPopular: false,
    duration: "3+ Hours",
    editedCount: 28,
    setupsCount: "2 Setups + Family",
    rawIncluded: true,
    description: "Ideal for families who wish to be part of the memories, this package includes two distinct setups along with parent and child portraits.",
    inclusions: [
      "1 setup with plain or minimal décor.",
      "1 customized themed décor setup, designed as per your preference.",
      "Special parent & child portraits.",
      "28 professionally edited images.",
      "All raw images provided.",
      "Location: Studio | Duration: 3 + Hours",
    ],
    serviceName: "Baby Photography",
    fallbackServiceId: 11,
    whatsappMessage: "Hello Jaya Photography! I'm interested in booking the Baby Photography - Radiance package (₹40,000) with parent portraits included.",
  },
  {
    id: "baby-starlight",
    category: "baby",
    title: "Baby Photography - StarLight",
    tier: "StarLight",
    price: "₹55,000",
    numericPrice: 55000,
    badge: "Luxury Grandeur",
    isPopular: false,
    duration: "3+ Hours",
    editedCount: 30,
    setupsCount: "2 Fully Themed + Family",
    rawIncluded: true,
    description: "Our most elaborate offering, perfect for those desiring a luxurious and detailed experience with premium setups and timeless portraits.",
    inclusions: [
      "2 fully themed décor setups, designed with premium elements.",
      "Heartwarming parent & child portraits.",
      "30 professionally edited images.",
      "All raw images provided.",
      "Location: Studio | Duration: 3 + Hours",
    ],
    serviceName: "Baby Photography",
    fallbackServiceId: 11,
    whatsappMessage: "Hello Jaya Photography! I'm interested in booking the Baby Photography - StarLight Luxury package (₹55,000).",
  },

  // ==========================================
  // Maternity Photoshoot
  // ==========================================
  {
    id: "maternity-classic",
    category: "maternity",
    title: "Maternity - Classic",
    tier: "Classic",
    price: "₹15,000",
    numericPrice: 15000,
    badge: "Studio Minimalist",
    isPopular: false,
    duration: "2 Hours",
    editedCount: 10,
    setupsCount: "1 Plain Backdrop",
    rawIncluded: true,
    description: "Cherish the very first moments of your journey with our package, designed to preserve memories forever.",
    inclusions: [
      "Portraits on a plain background with dramatic light play.",
      "One complimentary dress included.",
      "10 professionally edited pictures.",
      "All raw pictures provided.",
      "Location: Studio | Duration: 2 Hours",
    ],
    serviceName: "Maternity Photoshoot",
    fallbackServiceId: 1,
    whatsappMessage: "Hello Jaya Photography! I'm interested in booking the Maternity - Classic package (₹15,000).",
  },
  {
    id: "maternity-premium",
    category: "maternity",
    title: "Maternity - Premium",
    tier: "Premium",
    price: "₹25,000",
    numericPrice: 25000,
    badge: "Dual Setup",
    isPopular: false,
    duration: "2 Hours",
    editedCount: 20,
    setupsCount: "2 Setups (Themed + Plain)",
    rawIncluded: true,
    description: "Cherish the very first moments of your journey with our package, designed to preserve memories forever.",
    inclusions: [
      "Two Setups (One Themed + One Plain)",
      "Includes One complimentary dress.",
      "20 Edited Pictures.",
      "All RAW pictures.",
      "Location: Studio | Duration: 2 Hours",
    ],
    serviceName: "Maternity Photoshoot",
    fallbackServiceId: 1,
    whatsappMessage: "Hello Jaya Photography! I'm interested in booking the Maternity - Premium package (₹25,000).",
  },
  {
    id: "maternity-basic-elegance",
    category: "maternity",
    title: "Maternity - Basic Elegance",
    tier: "Basic Elegance",
    price: "₹35,000",
    numericPrice: 35000,
    badge: "Most Popular",
    isPopular: true,
    duration: "3+ Hours",
    editedCount: 20,
    setupsCount: "2 Setups (Themed + Plain)",
    rawIncluded: true,
    description: "Cherish the very first moments of your journey with our customized package, designed to preserve memories forever.",
    inclusions: [
      "One Themed Décor Setup – Beautifully designed as per your preference.",
      "One Plain Background Setup – Classic and elegant shots.",
      "20 Professionally Edited Images.",
      "All Raw Pictures Provided.",
      "Location: Studio | Duration: 3 + Hours",
    ],
    serviceName: "Maternity Photoshoot",
    fallbackServiceId: 1,
    whatsappMessage: "Hello Jaya Photography! I'd like to book the Maternity - Basic Elegance package (₹35,000). Please share upcoming availability.",
  },
  {
    id: "maternity-premium-portrait",
    category: "maternity",
    title: "Maternity - Premium Portrait",
    tier: "Premium Portrait",
    price: "₹40,000",
    numericPrice: 40000,
    badge: "Extended Variety",
    isPopular: false,
    duration: "3+ Hours",
    editedCount: 25,
    setupsCount: "3 Setups (1 Themed + 2 Plain)",
    rawIncluded: true,
    description: "Cherish the very first moments of your journey with our customized package, designed to preserve memories forever.",
    inclusions: [
      "One Themed Décor Setup – Beautifully designed as per your preference.",
      "Two Plain Background Setup – Classic and elegant shots.",
      "25 Professionally Edited Images.",
      "All Raw Pictures Provided.",
      "Location: Studio | Duration: 3 + Hours",
    ],
    serviceName: "Maternity Photoshoot",
    fallbackServiceId: 1,
    whatsappMessage: "Hello Jaya Photography! I'm interested in booking the Maternity - Premium Portrait package (₹40,000).",
  },
  {
    id: "maternity-luxury-signature",
    category: "maternity",
    title: "Maternity - Luxury Signature",
    tier: "Luxury Signature",
    price: "₹55,000",
    numericPrice: 55000,
    badge: "Haute Couture",
    isPopular: false,
    duration: "3+ Hours",
    editedCount: 30,
    setupsCount: "3 Setups (2 Themed + 1 Plain)",
    rawIncluded: true,
    description: "Cherish the very first moments of your journey with our premium setups and timeless maternity portraits.",
    inclusions: [
      "Two Themed Décor Setup – Beautifully designed as per your preference.",
      "One Plain Background Setup – Classic and elegant shots.",
      "30 Professionally Edited High-Resolution Images.",
      "All Raw Pictures Provided.",
      "Location: Studio | Duration: 3 + Hours",
    ],
    serviceName: "Maternity Photoshoot",
    fallbackServiceId: 1,
    whatsappMessage: "Hello Jaya Photography! I'm looking to book the Maternity - Luxury Signature package (₹55,000) for our upcoming baby.",
  },

  // ==========================================
  // Newborn Photography
  // ==========================================
  {
    id: "newborn-classic",
    category: "newborn",
    title: "Newborn - Classic",
    tier: "Classic",
    price: "₹15,000",
    numericPrice: 15000,
    badge: "Tender Beginnings",
    isPopular: false,
    duration: "2 Hours",
    editedCount: 10,
    setupsCount: "1 Décor Setup",
    rawIncluded: true,
    description: "Cherish the very first moments of your little one with our package, designed to preserve memories forever.",
    inclusions: [
      "One Decor Setup.",
      "Macro Shoot.",
      "10 Edited Pictures.",
      "Option to add family portraits: ₹4,500/-",
    ],
    serviceName: "Newborn Photography",
    fallbackServiceId: 2,
    whatsappMessage: "Hello Jaya Photography! I'm interested in the Newborn - Classic package (₹15,000).",
  },
  {
    id: "newborn-premium",
    category: "newborn",
    title: "Newborn - Premium",
    tier: "Premium",
    price: "₹25,000",
    numericPrice: 25000,
    badge: "Double Delight",
    isPopular: false,
    duration: "2 Hours",
    editedCount: 15,
    setupsCount: "2 Different Setups",
    rawIncluded: true,
    description: "Cherish the very first moments of your little one with our package, designed to preserve memories forever.",
    inclusions: [
      "Two Different Setups.",
      "Macro Shots Included.",
      "15 Beautifully Edited Pictures.",
      "Option to add family portraits: ₹4,500/-",
    ],
    serviceName: "Newborn Photography",
    fallbackServiceId: 2,
    whatsappMessage: "Hello Jaya Photography! I'm interested in the Newborn - Premium package (₹25,000).",
  },
  {
    id: "newborn-sweet-beginnings",
    category: "newborn",
    title: "Newborn - Sweet Beginnings",
    tier: "Sweet Beginnings",
    price: "₹35,000",
    numericPrice: 35000,
    badge: "Parents' Choice",
    isPopular: true,
    duration: "3+ Hours",
    editedCount: 20,
    setupsCount: "2 Themes (Plain + Styled)",
    rawIncluded: true,
    description: "Cherish the very first moments of your little one with our package, designed to preserve memories forever.",
    inclusions: [
      "2 Themes - One on a plain background & one beautifully styled.",
      "Adorable close-up pictures of your baby.",
      "20 professionally edited photos.",
      "All raw pictures included.",
      "Location: Studio | Duration: 3 + Hours",
    ],
    serviceName: "Newborn Photography",
    fallbackServiceId: 2,
    whatsappMessage: "Hello Jaya Photography! We'd love to book the Newborn - Sweet Beginnings package (₹35,000) for our new arrival.",
  },
  {
    id: "newborn-little-dreams",
    category: "newborn",
    title: "Newborn - Little Dreams",
    tier: "Little Dreams",
    price: "₹40,000",
    numericPrice: 40000,
    badge: "Family Included",
    isPopular: false,
    duration: "3+ Hours",
    editedCount: 25,
    setupsCount: "Themed + Backdrop + Parents",
    rawIncluded: true,
    description: "Cherish the very first moments of your little one with our package, designed to preserve memories forever.",
    inclusions: [
      "1 Themed setup + 1 plain backdrop for timeless elegance.",
      "Heartwarming pictures with parents to cherish forever.",
      "Close-up shots capturing tiny fingers, toes & expressions.",
      "25 professionally edited photos.",
      "All raw pictures included.",
      "Location: Studio | Duration: 3 + Hours",
    ],
    serviceName: "Newborn Photography",
    fallbackServiceId: 2,
    whatsappMessage: "Hello Jaya Photography! I'm interested in booking the Newborn - Little Dreams package (₹40,000) with parent portraits.",
  },
  {
    id: "newborn-everlasting-memories",
    category: "newborn",
    title: "Newborn - Everlasting Memories",
    tier: "Everlasting Memories",
    price: "₹55,000",
    numericPrice: 55000,
    badge: "Signature Heirloom",
    isPopular: false,
    duration: "3+ Hours",
    editedCount: 30,
    setupsCount: "3 Setups (2 Themed + 1 Plain) + Family",
    rawIncluded: true,
    description: "Cherish the very first moments of your little one with our package, designed to preserve memories forever.",
    inclusions: [
      "2 Gorgeous themes + 1 plain backdrop for variety.",
      "Beautiful family moments with parents included.",
      "Close-up shots of your tiny bundle of joy.",
      "30 professionally edited pictures.",
      "All original pictures delivered on a drive.",
      "Location: Studio | Duration: 3 + Hours",
    ],
    serviceName: "Newborn Photography",
    fallbackServiceId: 2,
    whatsappMessage: "Hello Jaya Photography! I'd like to book the luxury Newborn - Everlasting Memories package (₹55,000).",
  },
];

export const STUDIO_PROMISES = [
  {
    icon: "ShieldCheck",
    title: "100% Baby-Safe & Sanitized",
    description: "Warm temperature-controlled studio (26°C-28°C), organic sanitized wraps, and 10+ years of certified safe posing experience.",
  },
  {
    icon: "Sparkles",
    title: "Designer Wardrobe & Props",
    description: "Extensive collection of imported wraps, handcrafted headbands, vintage baskets, and luxury maternity flying gowns.",
  },
  {
    icon: "FolderDown",
    title: "All RAW Photos Included",
    description: "Every unedited full-resolution picture captured during your session is yours to keep, delivered on a private digital drive.",
  },
  {
    icon: "Palette",
    title: "Artistic Magazine-Grade Retouching",
    description: "Every selected portrait receives bespoke skin softening, color harmony correction, and fine-art heirloom enhancement.",
  },
];

export const PACKAGES_FAQ = [
  {
    question: "When is the best time to book my photoshoot session?",
    answer:
      "For Newborn sessions, the ideal time is during pregnancy (scheduling around your due date), with the shoot taking place between 5 to 25 days after birth when babies sleep deeply. For Maternity, between 28 to 34 weeks is best when the bump is beautifully rounded. For Baby milestone shoots, 6 to 12 months is perfect as babies learn to sit without support and show adorable expressions.",
  },
  {
    question: "Are costumes, gowns, and baby props included in the packages?",
    answer:
      "Yes! Our studio in Lucknow houses a curated collection of designer maternity gowns, organic baby wraps, bonnets, crowns, and custom-crafted theme backdrops. Specific packages also mention complimentary dresses or custom themed decors.",
  },
  {
    question: "Can parents and siblings participate in the photoshoot?",
    answer:
      "Absolutely! Several packages (such as Baby Radiance/StarLight, Newborn Little Dreams/Everlasting Memories) have parent and child portraits already included. For Classic and Premium tiers, family portraits can be added for a nominal fee of ₹4,500/-.",
  },
  {
    question: "How long does it take to receive our photos?",
    answer:
      "All uncompressed RAW photos are provided within 3 to 5 business days for your initial viewing and selection. Once you choose your favorite pictures for editing, our fine-art retouching takes approximately 2 to 3 weeks.",
  },
  {
    question: "How do I secure my preferred date and time slot?",
    answer:
      "You can click 'Book This Package' or contact us directly on WhatsApp (+91 93353 91320). A small advance booking token locks your studio slot, with the balance payable on the shoot day.",
  },
  {
    question: "What if my baby becomes fussy or needs feeding during the shoot?",
    answer:
      "We never rush our sessions! Our studio is equipped with a private mother & baby lounge. We build in plenty of time for feedings, diaper changes, snuggling, and soothing breaks to keep your little one happy and comfortable.",
  },
];
