// 🌟 Fallback Photography Services Dataset
export const FALLBACK_SERVICES = [
  {
    _id: "service-newborn-milestone",
    id: "s1",
    slug: "baby-milestone-photoshoot-lucknow",
    aliases: ["newborn-photography-lucknow", "baby-photography-lucknow"],
    title: "Newborn & Baby Milestone Photography",
    metaTitle: "Newborn & Baby Milestone Photography Lucknow | Jaya Photography",
    metaDescription: "Premier safety-first newborn and baby milestone photography studio in Sushant Golf City, Lucknow. 10+ years experience, sanitized props & private lounge.",
    metaKeywords: ["newborn photography lucknow", "baby milestone photoshoot lucknow", "baby photographer lucknow", "cake smash photoshoot lucknow"],
    category: "Newborn & Milestone",
    subtitle: "Safety-first luxury newborn and baby milestone portraits in Sushant Golf City, Lucknow.",
    description: "Welcoming a baby into the world is a momentous occasion filled with tender, fleeting moments. Our Sushant Golf City studio in Lucknow is specifically designed for delicate newborns and growing babies. We maintain strict hygiene, temperature-controlled warmth (26°C-28°C), and soft sanitized props so your little one remains relaxed throughout the session.",
    duration: "2 to 3 Hours",
    featured: true,
    coverImage: "https://images.unsplash.com/photo-1555252333-9f8e92e65df9?q=80&w=1200&auto=format&fit=crop",
    mainImage: "https://images.unsplash.com/photo-1555252333-9f8e92e65df9?q=80&w=1200&auto=format&fit=crop",
    features: [
      "100% Baby-safe, sanitized organic wraps, bonnets & props provided",
      "Heated & temperature-controlled studio environment (26°C - 28°C)",
      "Private mother & baby feeding and lounge space",
      "Solo baby poses, macro detail shots (fingers & toes), and parent bonding portraits",
      "High-resolution art-edited digital portraits with print release",
    ],
  },
  {
    _id: "service-maternity",
    id: "s2",
    slug: "maternity-photoshoot-lucknow",
    aliases: ["maternity-photography-lucknow"],
    title: "Maternity Photoshoot in Lucknow",
    metaTitle: "Maternity Photoshoot in Lucknow | Luxury Pregnancy Photography",
    metaDescription: "Celebrate your pregnancy glow with fine-art maternity photoshoots in Lucknow. Designer gowns, partner styling, and studio or outdoor locations.",
    metaKeywords: ["maternity photoshoot lucknow", "maternity photographer lucknow", "pregnancy shoot lucknow", "flying gown maternity shoot"],
    category: "Maternity",
    subtitle: "Celebrate your maternity journey with artistic fine-art portraits and designer gown styling.",
    description: "Maternity photography honors the beauty, strength, and anticipation of expecting mothers. We offer an extensive collection of designer flying gowns, lace robes, and elegant silhouettes in our Sushant Golf City studio or scenic outdoor locations across Lucknow.",
    duration: "1.5 to 2.5 Hours",
    featured: true,
    coverImage: "https://images.unsplash.com/photo-1519689680058-324335c77eba?q=80&w=1200&auto=format&fit=crop",
    mainImage: "https://images.unsplash.com/photo-1519689680058-324335c77eba?q=80&w=1200&auto=format&fit=crop",
    features: [
      "Access to luxury designer maternity gowns & accessories",
      "Professional hair & makeup assistance available on request",
      "Partner and sibling participation included at no extra cost",
      "Choice of indoor fine-art studio or outdoor sunset garden concepts",
      "Retouched high-definition digital gallery",
    ],
  },
  {
    _id: "service-family",
    id: "s3",
    slug: "family-photoshoot",
    aliases: ["family-portrait", "family-photography-lucknow"],
    title: "Family Portrait Photography",
    metaTitle: "Family Portrait Photography in Lucknow | Jaya Photography",
    metaDescription: "Create everlasting family heirlooms with professional family portrait sessions in Lucknow. Warm poses, natural interactions, and multigenerational shoots.",
    metaKeywords: ["family photoshoot lucknow", "family portraits lucknow", "family photographer lucknow"],
    category: "Family",
    subtitle: "Warm, candid, and elegant family portraits capturing genuine togetherness.",
    description: "Family portraits preserve the unique bond, laughter, and generations of love in your family. Whether celebrating a family milestone or creating annual heirlooms, we guide you through relaxed posing that brings out authentic smiles.",
    duration: "1.5 to 2 Hours",
    featured: true,
    coverImage: "https://images.unsplash.com/photo-1511895426328-dc8714191300?q=80&w=1200&auto=format&fit=crop",
    mainImage: "https://images.unsplash.com/photo-1511895426328-dc8714191300?q=80&w=1200&auto=format&fit=crop",
    features: [
      "Multigenerational family portrait setups",
      "Wardrobe coordination & color scheme consultation",
      "Candid laughter & natural emotion capture",
      "High-resolution edited digital portraits ready for luxury framing",
    ],
  },
  {
    _id: "service-toddler",
    id: "s4",
    slug: "toddler-photoshoot-lucknow",
    aliases: ["toddler-beyond-photoshoot-lucknow"],
    title: "Toddler & Kids Photoshoot",
    metaTitle: "Toddler & Kids Photoshoot in Lucknow | Jaya Photography",
    metaDescription: "Fun, energetic, and playful toddler photoshoots in Lucknow. Capturing early childhood expressions, birthdays, and milestones.",
    metaKeywords: ["toddler photoshoot lucknow", "kids photographer lucknow", "birthday photoshoot lucknow"],
    category: "Toddler & Kids",
    subtitle: "Playful toddler and kids photo sessions capturing innocent smiles and curiosity.",
    description: "Toddlers are full of energy, curiosity, and charming expressions. Our sessions are styled around fun, interactive play so your child stays happily engaged while we capture genuine giggles and expressions.",
    duration: "1 to 2 Hours",
    featured: false,
    coverImage: "https://images.unsplash.com/photo-1544126592-807ade215a0b?q=80&w=1200&auto=format&fit=crop",
    mainImage: "https://images.unsplash.com/photo-1544126592-807ade215a0b?q=80&w=1200&auto=format&fit=crop",
    features: [
      "Playful props, toys, and interactive backdrops",
      "Patient photographer trained in handling toddlers",
      "Birthday milestone styling & custom setups",
      "Artistically retouched digital gallery",
    ],
  },
  {
    _id: "service-fashion",
    id: "s5",
    slug: "fashion-photographer-lucknow",
    aliases: ["professional-fashion-photography", "fashion-photography"],
    title: "Fashion & Creative Portrait Photography",
    metaTitle: "Fashion & Portrait Photography in Lucknow | Jaya Photography",
    metaDescription: "Professional fashion, portfolio, and creative portrait photography in Lucknow. Studio lighting, high-fashion styling, and model portfolios.",
    metaKeywords: ["fashion photographer lucknow", "model portfolio lucknow", "portrait photography lucknow"],
    category: "Fashion & Portrait",
    subtitle: "High-end fashion portraiture, creative concepts, and model portfolios in Lucknow.",
    description: "Elevate your professional portfolio or personal brand with high-fashion portrait photography. Featuring professional studio lighting, editorial posing guidance, and high-end retouching.",
    duration: "2 to 4 Hours",
    featured: false,
    coverImage: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=1200&auto=format&fit=crop",
    mainImage: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=1200&auto=format&fit=crop",
    features: [
      "Editorial lighting & high-fashion backdrop options",
      "Professional posing direction",
      "Multiple outfit changes & look variations",
      "Magazine-quality high-end skin and color retouching",
    ],
  },
  {
    _id: "service-theme",
    id: "s6",
    slug: "theme-photoshoot-lucknow",
    aliases: ["theme-photoshoot-lucknow-"],
    title: "Themed Concept Photoshoot",
    metaTitle: "Themed Concept Photoshoot in Lucknow | Jaya Photography",
    metaDescription: "Custom themed concept photoshoots in Lucknow for birthdays, festivals, and creative concepts.",
    metaKeywords: ["theme photoshoot lucknow", "concept photography lucknow"],
    category: "Themed Shoot",
    subtitle: "Custom themed concepts and magical set designs brought to life.",
    description: "Turn your creative vision into reality with our bespoke themed photoshoots. From fairytale setups to traditional festive themes, we design custom sets tailored to your celebration.",
    duration: "2 to 3 Hours",
    featured: false,
    coverImage: "https://images.unsplash.com/photo-1519689680058-324335c77eba?q=80&w=1200&auto=format&fit=crop",
    mainImage: "https://images.unsplash.com/photo-1519689680058-324335c77eba?q=80&w=1200&auto=format&fit=crop",
    features: [
      "Bespoke set design & custom prop arrangement",
      "Themed costume assistance & styling",
      "Creative color grading & art editing",
      "Digital gallery release",
    ],
  },
];

// Helper to find service by slug or alias
export function getFallbackServiceBySlug(slug) {
  if (!slug) return null;
  const normalizedSlug = slug.toLowerCase().trim();
  return (
    FALLBACK_SERVICES.find(
      (s) =>
        s.slug.toLowerCase() === normalizedSlug ||
        (Array.isArray(s.aliases) && s.aliases.some((a) => a.toLowerCase() === normalizedSlug))
    ) || null
  );
}
